# Generated by Django 5.0.1 on 2024-09-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Countryid', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Countrynm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capitalid', models.IntegerField(max_length=10)),
                ('Capitalnm', models.CharField(max_length=50)),
                ('Countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
