# Generated by Django 5.0.1 on 2024-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='COMM',
            field=models.FloatField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='GRADE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='HISAL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salgrade',
            name='LOSAL',
            field=models.IntegerField(),
        ),
    ]
